language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=20

android:
  components:
    - android-23
    - build-tools-23.0.0
    - extra-android-m2repository
    - extra-android-support

before_script:
  # Create, start and wait for emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build checkstyle connectedAndroidTest -PdisablePreDex