language: android
sudo: false

android:
  components:
    - build-tools-23.0.0
    - android-23
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-21

before_install:
 - chmod +x gradlew

after_success:
 - chmod +x ./upload-gh-pages.sh
 - ./upload-gh-pages.sh

before_script:
 - cd $TRAVIS_BUILD_DIR/app/src/main/res/
 - wget https://crowdin.com/downloads/crowdin-cli.jar
 - java -jar crowdin-cli.jar download
 - rm crowdin-cli.jar
 - cd $TRAVIS_BUILD_DIR
 - git config --global user.email "glucosioproject@gmail.com"
 - git config --global user.name "Glucat"
 - git add -f .
 - git remote rm origin
 - git remote add origin https://glucat:$GITHUB_API_KEY@github.com/Glucosio/android
 - git add -f .
 - git commit -m "Automatic translations import (build  $TRAVIS_BUILD_NUMBER)."
 - git push origin develop

script:
 - ./gradlew clean build